#!/usr/bin/env bash

_path="/sys/class/power_supply/"
_battery=$(find "${_path}" -type l -name 'BAT*' -printf "%f\n")
_charger=$(find "${_path}" -type l -name 'AC' -printf "%f\n")

if [[ -e "${_path}${_battery}/capacity" ]]; then
  _batteryLevel=$(cat "${_path}${_battery}"/capacity)
  _isConnected=$(cat "${_path}${_charger}"/online)
fi

if [[ "${_batteryLevel}" != "" ]]; then
  _outputString=""

  if [[ $_isConnected == "1" ]]; then
    _outputString="${_outputString}" # AC
  else
    _outputString="${_outputString}" # BAT
  fi

  if [[ "${_batteryLevel}" -lt 10 ]]; then
    notify-send 'Low Battery' 'Your battery is below 10%.'
    _outputString="!${_outputString}"
  fi

  _outputString="${_outputString}""${_batteryLevel}"

  echo "${_outputString}"
fi
