#!/usr/bin/env bash

# Set threshold for warning
_warningThreshold="${1:-10}"

# Path to device information
_path="/sys/class/power_supply/"

# Find battery and ac-adapter name
_battery=$(find "${_path}" -type l -name 'BAT*' -printf "%f\n")
_charger=$(find "${_path}" -type l -name 'AC' -printf "%f\n")

# Set charge percentage and ac-adapter status
if [[ ! -e "${_path}${_battery}/capacity" ]]; then exit 1; fi
_batteryLevel=$(cat "${_path}${_battery}"/capacity)
_isConnected=$(cat "${_path}${_charger}"/online)

# Warn user for battery levels below certain threshold
if [[ "${_batteryLevel}" -lt "${_warningThreshold}" ]]; then
  notify-send 'Low Battery' 'Your battery is below 10%.'
fi

# Hide if ac-adapter is connected
if [[ $_isConnected == "1" ]] &&
   [[ $_batteryLevel -gt $_warningThreshold ]]; then
  _batteryLevel=""
fi

echo "${_batteryLevel}"
